variable "vpc_id" {}
variable "subnet_id" {}
variable "ami_id" {}
variable "instance_type" {}
variable "key_name" {}
variable "data_volume_size" {}
variable "nfs_share_path" {}
variable "cluster_name" {}
variable "nfs_ip" {}
variable "pri_sub_cidr" {}
variable "vpc_cidr" {}