variable "private_subnet_id" {}
variable "bootstrap_ip" {}
variable "control_plane_ips" {}
variable "worker_ips" {}
variable "RHCOS" {}
variable "bootstrap_sg" {}
variable "master_sg" {}
variable "worker_sg" {}
variable "key_name" {}
variable "pullSecret" {}
variable "ocp_instance" {}
variable "cluster_name" {}
variable "name" {}
variable "domain_name" {}
variable "ec2_ssh_key" {}
variable "sgw_instance" {}
variable "control_plane_count" {}
variable "worker_count" {}
variable "finish_mgr" {}
variable "manager_ip" {}