variable "vpc_id" {}
variable "public_subnet_id" {}
variable "manager_ip" {}
variable "lb_ip" {}
variable "dns_ip" {}
variable "monitor_ip" {}
variable "AL2023" {}
variable "manager_sg" {}
variable "lb_sg" {}
variable "dns_sg" {}
variable "monitor_sg" {}
variable "control_plane_count" {}
variable "worker_count" {}
variable "key_name" {}
variable "pullSecret" {}
variable "server_instance" {}
variable "cluster_name" {}
variable "name" {}
variable "domain_name" {}
variable "ec2_ssh_key" {}
variable "bootstrap_ip" {}
variable "control_plane_ips" {}
variable "worker_ips" {}
variable "db_ips" {}
variable "nat_ip" {}
variable "nfs_ip" {}
variable "gitea_ip" {}
# variable "waf_ip" {}
# variable "waf_sg" {}
