variable "vpc_id" {}
variable "public_subnet_id" {}
variable "private_subnet_id" {}
variable "manager_ip" {}
variable "lb_ip" {}
variable "dns_ip" {}
variable "bootstrap_ip" {}
variable "control_plane_ips" {}
variable "worker_ips" {}
variable "RHCOS" {}
variable "AL2023" {}
variable "manager_sg" {}
variable "lb_sg" {}
variable "dns_sg" {}
variable "bootstrap_sg" {}
variable "master_sg" {}
variable "worker_sg" {}
variable "key_name" {}
variable "pullSecret" {}
variable "ocp_instance" {}
variable "server_instance" {}
variable "cluster_name" {}
variable "domain_name" {}
variable "ec2_ssh_key" {}